# List of random sentences for the Chromolexia Translator
SENTENCES = [
    "Gnomes are awesome at gardening",
    "Dragons sleep in mountain caves",
    "Knights protect the sacred realm",
    "Wizards study ancient tomes",
    "Blacksmiths forge mighty swords",
    "Mermaids sing enchanting songs",
    "Vikings sailed vast oceans",
    "Castles stand tall and proud",
    "Pharaohs ruled ancient Egypt",
    "Rome was built in many days",
    "Spartans were fierce warriors",
    "Samurai follow the bushido code",
    "Ninjas move like shadows",
    "Pirates seek hidden treasure",
    "Druids worship nature spirits",
    "Trolls live under bridges",
    "Elves craft magical items",
    "Dwarves mine precious gems",
    "Unicorns prance in meadows",
    "Phoenix rises from ashes",
    "Centaurs roam wild forests",
    "Astronomers map the stars",
    "Alchemists seek gold formula",
    "Peasants tend the fields",
    "Kings wear golden crowns",
    "Queens rule with wisdom",
    "Jesters tell funny jokes",
    "Merchants trade exotic goods",
    "Sailors navigate by stars",
    "Monks transcribe ancient texts",
    "Warriors train with swords",
    "Archers perfect their aim",
    "Healers gather herbs",
    "Bakers make fresh bread",
    "Farmers grow crops",
    "Scholars read old books",
    "Artists paint landscapes",
    "Musicians play at feasts",
    "Guards patrol city walls",
    "Squires serve noble knights",
    "Dragons breathe fire",
    "Witches brew potions",
    "Ghosts haunt old castles",
    "Wolves howl at moon",
    "Bears fish in streams",
    "Eagles soar high above",
    "Horses gallop freely",
    "Lions rule the plains",
    "Tigers stalk prey",
    "Foxes outsmart hunters",
    "Owls watch at night",
    "Ravens carry messages",
    "Cats chase mice",
    "Dogs guard homes",
    "Rabbits hop quickly",
    "Deer graze peacefully",
    "Butterflies bring messages",
    "Bees make honey",
    "Ants work together",
    "Spiders weave webs",
    "Snakes slide silently",
    "Fish swim deep",
    "Crabs walk sideways",
    "Turtles move slowly",
    "Frogs jump high",
    "Birds sing songs",
    "Peacocks display feathers",
    "Earth spins always",
    "Stars shine bright",
    "Rivers flow endlessly",
    "Mountains reach skyward",
    "Trees grow tall",
    "Flowers bloom bright",
    "Wind blows free",
    "Rain falls softly",
    "Snow covers earth",
    "Lightning strikes fast",
    "Thunder rolls loud",
    "Clouds float by",
    "Rainbows arch high",
    "Waterfalls flow down",
    "Volcanoes erupt mighty",
    "Geysers shoot up",
    "Crystals grow slowly",
    "Diamonds sparkle bright",
    "Gold gleams yellow",
    "Silver shines white",
    "Bronze stays strong",
    "Iron rusts red",
    "Steel holds sharp",
    "Glass breaks clean",
    "Wood burns hot",
    "Stone stays still",
    "Ice freezes clear",
    "Steam rises high",
    "Fire burns bright",
    "Water flows fast",
    "Air moves free",
    "Magic flows eternal",
    "Time marches forward",
    "Life finds way",
    "Hope springs eternal",
    "Love conquers all",
    "Peace brings joy",
    "Wisdom comes slowly",
    "Knowledge brings power",
    "Truth stays constant"
]